config/routes.rb
Rails.application.routes.draw do
  scope '', module: 'public' do
    namespace :locations do
      resource :data, only: [:show]
    end

    resources :locations, only: [:show]
  end

  namespace :admin do
    root to: 'campaigns#index', as: :root
    resources :campaigns
    resources :locations
    resources :mappings
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
# == Schema Information
#
# Table name: campaigns
#
#  id         :integer          not null, primary key
#  name       :string
#  site_data  :json
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Campaign < ApplicationRecord
  include SiteUploader[:site]
  acts_as_taggable

  has_many :location_campaigns, dependent: :destroy
  has_many :locations, through: :location_campaigns

  validates :name, presence: true
  validates :site, presence: true

  after_save :activate_site
  before_destroy :deactivate_site

  def activate_site
    SiteUnzipper.new(self).call
  end

  def deactivate_site
    SiteDeleter.new(self).call
  end
end

app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id         :integer          not null, primary key
#  name       :string
#  location   :point
#  radius     :float
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Location < ApplicationRecord
  attribute :location, :legacy_point

  has_many :location_campaigns, dependent: :destroy
  has_many :campaigns, through: :location_campaigns

  validates :name, presence: true
  validates :location, presence: true
  validates :radius, presence: true

  def longitude
    (location || []).first
  end

  def latitude
    (location || []).last
  end

  def longitude=(value)
    self.location ||= []
    self.location[0] = value
  end

  def latitude=(value)
    self.location ||= []
    self.location[1] = value
  end
end

app/models/location_campaign.rb
# == Schema Information
#
# Table name: location_campaigns
#
#  id          :integer          not null, primary key
#  location_id :integer
#  campaign_id :integer
#  points      :integer          default(0), not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class LocationCampaign < ApplicationRecord
  belongs_to :location
  belongs_to :campaign
end

app/models/mapping.rb
# == Schema Information
#
# Table name: mappings
#
#  id              :integer          not null, primary key
#  twitter_user_id :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  display_name    :string           default(""), not null
#

class Mapping < ApplicationRecord
  acts_as_taggable

  validates :twitter_user_id, presence: true, uniqueness: true
end

app/controllers/admin/campaigns_controller.rb
module Admin
  class CampaignsController < ResourcefulController
    private

    def permitted_attributes
      [:name, :site, :site_data, :tag_list]
    end
  end
end

app/controllers/admin/locations_controller.rb
module Admin
  class LocationsController < ResourcefulController
    private

    def permitted_attributes
      [:name, :longitude, :latitude, :radius]
    end
  end
end

app/controllers/admin/mappings_controller.rb
module Admin
  class MappingsController < ResourcefulController
    private

    def permitted_attributes
      [:twitter_user_id, :tag_list, :display_name]
    end
  end
end

app/controllers/admin/resourceful_controller.rb
module Admin
  class ResourcefulController < AdminController
    def index
      @collection = scope
                    .order(order)
                    .paginate(page: params[:page], per_page: per_page)
    end

    def show
      @record ||= load_record
    end

    def new
      @record ||= scope.new
    end

    def create
      @record ||= scope.new(permitted_params)
      if @record.save
        redirect_to [:admin, index_key]
      else
        render 'new'
      end
    end

    def edit
      @record ||= load_record
    end

    def update
      @record ||= load_record
      if @record.update(permitted_params)
        redirect_to [:admin, index_key]
      else
        render 'new'
      end
    end

    def destroy
      @record ||= load_record
      @record.destroy
      redirect_to [:admin, index_key]
    end

    private

    def load_record
      scope.find(params[:id])
    end

    def scope
      model_class.all
    end

    def per_page
      16
    end

    def model_name
      @model_name ||= begin
        controller_name =
          self.class.name.gsub!('Admin::', '').gsub!('Controller', '')
        controller_name.singularize
      end
    end

    def index_key
      @index_key ||= model_name.pluralize.downcase.to_sym
    end

    def model_class
      @model_class ||= model_name.safe_constantize
    end

    def order
      { created_at: :desc }
    end

    def permitted_params
      root_key = model_name.downcase.to_sym
      return {} unless params[root_key]
      params.require(root_key).permit(permitted_attributes)
    end

    def permitted_attributes
      []
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def layout_file
    'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  layout :layout_by_resource

  def layout_by_resource
    if request.xhr?
      false
    else
      layout_file
    end
  end

  def layout_file
    'public'
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def layout_file
    'public'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/campaigns/_form.slim
= simple_form_for [:admin, campaign] do |f|
  .row
    .col-xs-12
      =f.input :name
    .col-xs-12
      =f.input :tag_list, as: :text

  .row
    .col-xs-12
      = f.input :site, as: :shrine

    - if f.object.site && f.object.site.exists?
      .col-xs-12
        = link_to f.object.site.url, class: 'btn btn-success btn-lg'
          = icon('download')
          | Download

  .row
    .col-xs-12
      hr

      button.btn.btn-success.btn-lg
        = icon('check')
        | Save

      = link_to [:admin, :campaigns], class: 'btn btn-primary btn-lg'
        = icon('chevron-left')
        | Back

    .col-xs-12
      - if f.object.created_at.present?
        p.help-block Created at: #{f.object.created_at}

      - if f.object.updated_at.present?
        p.help-block Updated at: #{f.object.updated_at}

app/views/admin/campaigns/_row.slim
tr
  td = campaign.name
  td
    .pull-right
      = link_to [:edit, :admin, campaign], class: 'btn btn-xs btn-warning'
        = icon(:edit)
        | Edit
      = link_to [:admin, campaign], class: 'btn btn-xs btn-danger', method: :delete
        = icon('trash-o')
        | Delete

app/views/admin/campaigns/edit.slim
h1 Edit campaign

= render 'form', campaign: @record

app/views/admin/campaigns/index.slim
h1 Campaigns

.row
  .col-xs-12
    table.table.table-striped
      thead
        tr
          th Name
          th
            .pull-right
              = link_to [:new, :admin, :campaign], class: 'btn btn-xs btn-primary' do
                = icon(:plus)
                | Add
      tbody
        - @collection.each do |campaign|
          = render 'row', campaign: campaign

  .col-xs-12
    .pagination-container
      = will_paginate @collection, renderer: BootstrapPagination::Rails

app/views/admin/campaigns/new.slim
h1 New campaign

= render 'form', campaign: @record

app/views/admin/locations/_form.slim
= simple_form_for [:admin, campaign] do |f|
  .row
    .col-xs-12
      = f.input :name
    .col-xs-12
      = f.input :radius

  .row
    .col-xs-12
      = f.label :location
      = text_field_tag :search, nil, id: :location_search
    .col-xs-12
      .map#map data-map='true' data-search-field="#location_search" data-picker="true" data-latitude-input="#location_latitude" data-longitude-input="#location_longitude"
    .col-md-6
      = f.input :longitude
    .col-md-6
      = f.input :latitude

  .row
    .col-xs-12
      hr

      button.btn.btn-success.btn-lg
        = icon('check')
        | Save

      = link_to [:admin, :campaigns], class: 'btn btn-primary btn-lg'
        = icon('chevron-left')
        | Back

    .col-xs-12
      - if f.object.created_at.present?
        p.help-block Created at: #{f.object.created_at}

      - if f.object.updated_at.present?
        p.help-block Updated at: #{f.object.updated_at}

app/views/admin/locations/_row.slim
tr
  td = location.name
  td
    .pull-right
      = link_to [:edit, :admin, location], class: 'btn btn-xs btn-warning'
        = icon(:edit)
        | Edit
      = link_to [:admin, location], class: 'btn btn-xs btn-danger', method: :delete
        = icon('trash-o')
        | Delete

app/views/admin/locations/edit.slim
h1 Edit campaign

= render 'form', campaign: @record

app/views/admin/locations/index.slim
h1 Locations

.row
  .col-xs-12
    table.table.table-striped
      thead
        tr
          th Name
          th
            .pull-right
              = link_to [:new, :admin, :location], class: 'btn btn-xs btn-primary' do
                = icon(:plus)
                | Add
      tbody
        - @collection.each do |location|
          = render 'row', location: location

  .col-xs-12
    .pagination-container
      = will_paginate @collection, renderer: BootstrapPagination::Rails

app/views/admin/locations/new.slim
h1 New campaign

= render 'form', campaign: @record

app/views/admin/mappings/_form.slim
= simple_form_for [:admin, mapping] do |f|
  .row
    .col-md-6
      = f.input :display_name
    .col-md-6
      = f.input :twitter_user_id

  .row
    .col-xs-12
      = f.input :tag_list, as: :text

  .row
    .col-xs-12
      hr

      button.btn.btn-success.btn-lg
        = icon('check')
        | Save

      = link_to [:admin, :mappings], class: 'btn btn-primary btn-lg'
        = icon('chevron-left')
        | Back

    .col-xs-12
      - if f.object.created_at.present?
        p.help-block Created at: #{f.object.created_at}

      - if f.object.updated_at.present?
        p.help-block Updated at: #{f.object.updated_at}

app/views/admin/mappings/_row.slim
tr
  td = mapping.display_name
  td
    .pull-right
      = link_to [:edit, :admin, mapping], class: 'btn btn-xs btn-warning'
        = icon(:edit)
        | Edit
      = link_to [:admin, mapping], class: 'btn btn-xs btn-danger', method: :delete
        = icon('trash-o')
        | Delete

app/views/admin/mappings/edit.slim
h1 Edit mapping

= render 'form', mapping: @record

app/views/admin/mappings/index.slim
h1 Mappings

.row
  .col-xs-12
    table.table.table-striped
      thead
        tr
          th Name
          th
            .pull-right
              = link_to [:new, :admin, :mapping], class: 'btn btn-xs btn-primary' do
                = icon(:plus)
                | Add
      tbody
        - @collection.each do |mapping|
          = render 'row', mapping: mapping

  .col-xs-12
    .pagination-container
      = will_paginate @collection, renderer: BootstrapPagination::Rails

app/views/admin/mappings/new.slim
h1 New mapping

= render 'form', mapping: @record

app/views/admin/shared/_navigation.slim
nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed data-toggle="collapse" data-target="#navigation"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar

      = link_to admin_root_path, class: 'navbar-brand' do
        | Junction 2016

    .collapse.navbar-collapse#navigation
      ul.nav.navbar-nav.navbar-right
        = active_link_to [:admin, :campaigns], active: :inclusive, wrap_tag: :li do
          = icon('file-text-o')
          | Campaigns
        = active_link_to [:admin, :locations], active: :inclusive, wrap_tag: :li do
          = icon('map-marker')
          | Locations
        = active_link_to [:admin, :mappings], active: :inclusive, wrap_tag: :li do
          = icon('tags')
          | Mappings

app/views/layouts/admin.slim
html
  head
    title Junction2016
    = csrf_meta_tags
    = stylesheet_link_tag 'admin/application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'admin/application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'https://maps.googleapis.com/maps/api/js?sensor=false&libraries=places'
    = javascript_include_tag 'https://cdn.rawgit.com/googlemaps/v3-utility-library/master/markerclustererplus/src/markerclusterer.js'
    = javascript_include_tag 'https://cdn.rawgit.com/googlemaps/v3-utility-library/master/richmarker/src/richmarker-compiled.js'
    = javascript_include_tag 'https://cdn.rawgit.com/googlemaps/v3-utility-library/master/infobox/src/infobox_packed.js'

  body
    = render 'admin/shared/navigation'
    .container
      = yield

app/views/layouts/public.slim
html
  head
    title Junction2016
    = csrf_meta_tags
    = stylesheet_link_tag 'public/application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'public/application', 'data-turbolinks-track': 'reload'

  body data-location-id="#{@location.try(:id)}"
    = yield